<?php

namespace App\Tests;

use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

class DatabaseDependentTestCase extends KernelTestCase
{

    /** @var EntityManagerInterface */
    protected $entityManager;

    public function setUp(): void
    {
        $kernel = self::bootKernel();

        $this->entityManager = $kernel->getContainer()->get('doctrine')->getManager();
//        parent::setUp(); // TODO: Change the autogenerated stub
    }


    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub

        $this->entityManager->close();
        $this->entityManager = null;
    }

}